export const themes = {
  primary: {
    BG: {
      primary: '#E92518',
      secondary: 'white',
      tertiary: '#E7ECF1',
      active: '#E92518',
      primaryItem: '#E92518',
      disable: '#F9F9FC',
      whiteOpacity: 'rgba(255, 255, 255, 0.1)',
      white: '#FFFFFF',
    },
    text: {
      primary: 'white',
      secondary: 'black',
      active: 'red',
    },
    bottomTab: {
      primaryBG: '#E92518',
      secondaryBG: 'white',
      primary: '#010101',
      disable: '#B2BCC4',
    },
    input: {
      error: 'red',
      primary: '#e6ffec',
    },
    icon: {
      primary: 'black',
      secondary: '#585858',
      active: '#E92518',
      disable: '#B2BCC4',
    },
    checkBox: {
      border: '#E92518',
      background: '#E92518',
      check: '#FFFFFF',
      uncheckBackground: '#FFFFFF',
    },
    calendar: {
      active: '#E92518',
      activeText: 'white',
      disableText: '#B7B7B7',
      primaryText: '#010101',
      buttonColor: '#F7F7FA',
      divider: '#B2BCC4',
    },
  },
  dark: {
    BG: {
      primary: '#E92518',
      secondary: 'white',
      tertiary: '#E7ECF1',
      active: '#E92518',
      primaryItem: '#E92518',
      disable: '#F9F9FC',
      whiteOpacity: 'rgba(255, 255, 255, 0.1)',
      white: '#FFFFFF',
    },
    input: {
      error: 'red',
      primary: '#e6ffec',
    },
    text: {
      primary: 'white',
      secondary: 'black',
      active: 'red',
    },
    bottomTab: {
      primaryBG: '#E92518',
      secondaryBG: 'white',
      primary: '#E92518',
      disable: '#AFAFAF',
    },
    icon: {
      primary: 'black',
      secondary: '#585858',
      active: '#E92518',
      disable: '#B2BCC4',
    },
    checkBox: {
      border: '#E92518',
      background: '#E92518',
      check: '#FFFFFF',
      uncheckBackground: '#FFFFFF',
    },
    calendar: {
      active: '#E92518',
      activeText: 'white',
      disableText: '#B7B7B7',
      primaryText: '#010101',
      buttonColor: '#F7F7FA',
      divider: '#B2BCC4',
    },
  },
};
